# Create a dependabot.yml file in the .github directory to configure Dependabot for your repository.
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(deps)"