name: Demande d'évolution
description: Proposer une fonctionnalité ou une amélioration
labels: ["enhancement"]
body:
  - type: textarea
    id: besoin
    attributes:
      label: Besoin
      description: Quel problème ou quelle limitation cette proposition résout-elle ?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
